### ISSUE TITLE
Update rpm.spec file to delete cached chart images 

### ISSUE THREAD

**Issue by bamelegari** [ua-snap/snap-www#136] opened 2013-03-19 19:43 UTC
Was: several exported charts do not create newlines in the text underneath the chart body.  Text/content below gives context.

expected:
In an exported chart, the bottom text (reading "Due to the variability...") has newlines at points similar to where it does when the chart is displayed in its embedded form on the webpage and is therefore readable and looks nice.

actual:
Text runs off the edge of the image, being cut around the word "trends".

This happens intermittently on both high resolution and low resolution pngs and svgs. There are some images of all types with the issue and some without, but it is common enough that it does not seem to be any sort of isolated occurrence.

a good example is the high resolution export of this chart: http://www.snap.uaf.edu/charts.php#community=202&dataset=1&scenario=a1b&units=standard&variability=0

**Comment by bamelegari** [comment] 2013-04-08 16:24
addendum: the issue seems to manifest differently in the svgs than in the png exports. The svgs cut off at different points or not at all depending on what program you use to view them. Not so with the others.

**Comment by bamelegari** [comment] 2013-04-10 16:52
Update: turns out the charts that were being served were just very old, cached charts. Clearing the cache and re-exporting seems (so far) to fix the problem (and produce a chart with a color scheme consistent with the one that the user sees on the webpage). Need to develop a solution to prevent that from happening again.

**Comment by brucecrevensten** [comment] 2013-04-12 15:15
Suggestion: make deleting the cached images part of a web site update?
 Happens often enough that it'd likely rinse out bad/stale ones on a
regular basis.

On Wed, Apr 10, 2013 at 12:52 PM, bamelegari notifications@github.comwrote:

> Update: turns out the charts that were being served were just very old,
> cached charts. Clearing the cache and re-exporting seems (so far) to fix
> the problem (and produce a chart with a color scheme consistent with the
> one that the user sees on the webpage). Need to develop a solution to
> prevent that from happening again.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/136#issuecomment-16186926
> .

## 

*Bruce Crevensten, Programmer
*
(ACUASI) Alaska Center for UAS Integration
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by bamelegari** [comment] 2013-07-19 22:29
added bash commands to jenkins build

**Comment by brucecrevensten** [comment] 2013-07-28 13:21
I haven't yet found the branch in which this code change is handled; since the issue was fixed by flushing files on the server, I'm marking this ticket as 'reviewed' for this milestone, but the relevant code should be found + confirmed merged to master so this doesn't happen again.  (And, reviewed to ensure nothing dangerous happens on update.)

**Closed as completed** 2013-08-15 22:23 UTC
